/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ListImport } from './routes/list'
import { Route as IndexImport } from './routes/index'
import { Route as PokemonNumberImport } from './routes/pokemon.$number'

// Create/Update Routes

const ListRoute = ListImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PokemonNumberRoute = PokemonNumberImport.update({
  id: '/pokemon/$number',
  path: '/pokemon/$number',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListImport
      parentRoute: typeof rootRoute
    }
    '/pokemon/$number': {
      id: '/pokemon/$number'
      path: '/pokemon/$number'
      fullPath: '/pokemon/$number'
      preLoaderRoute: typeof PokemonNumberImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/list': typeof ListRoute
  '/pokemon/$number': typeof PokemonNumberRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/list': typeof ListRoute
  '/pokemon/$number': typeof PokemonNumberRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/list': typeof ListRoute
  '/pokemon/$number': typeof PokemonNumberRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/list' | '/pokemon/$number'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/list' | '/pokemon/$number'
  id: '__root__' | '/' | '/list' | '/pokemon/$number'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListRoute: typeof ListRoute
  PokemonNumberRoute: typeof PokemonNumberRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListRoute: ListRoute,
  PokemonNumberRoute: PokemonNumberRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/list",
        "/pokemon/$number"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/list": {
      "filePath": "list.tsx"
    },
    "/pokemon/$number": {
      "filePath": "pokemon.$number.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
